import { BillingPlanItem } from "@/types/billing";

const NOW = "2026-01-01T00:00:00.000Z";

/** Static catalog for public pricing when the billing API is unavailable. */
export const STATIC_BILLING_PLANS: BillingPlanItem[] = [
  {
    id: "static_free_trial",
    plan_code: "free_trial",
    name: "Free Trial",
    description: "Evaluate ProposalIQ with core workflow features.",
    stripe_price_id: null,
    stripe_product_id: null,
    billing_cycle: "trial",
    price_cents: 0,
    currency: "usd",
    features: [
      "5 proposals per month",
      "Basic job analysis",
      "1 knowledge base file",
      "Email support",
    ],
    limits: {
      proposals_per_month: 5,
      job_analyses_per_month: 10,
      knowledge_base_files: 1,
      team_members: 1,
      workspaces: 1,
      trial_days: 14,
    },
    is_active: true,
    is_public: true,
    sort_order: 1,
    created_at: NOW,
    updated_at: NOW,
    price_display: "Free",
    is_purchasable: false,
    is_stripe_linked: false,
  },
  {
    id: "static_pro",
    plan_code: "pro",
    name: "Pro",
    description: "For individual business developers winning more contracts.",
    stripe_price_id: null,
    stripe_product_id: null,
    billing_cycle: "monthly",
    price_cents: 1900,
    currency: "usd",
    features: [
      "Unlimited proposals",
      "Advanced AI analysis",
      "10 knowledge base files",
      "Priority support",
    ],
    limits: {
      proposals_per_month: null,
      job_analyses_per_month: null,
      knowledge_base_files: 10,
      team_members: 1,
      workspaces: 1,
    },
    is_active: true,
    is_public: true,
    sort_order: 2,
    created_at: NOW,
    updated_at: NOW,
    price_display: "$19/mo",
    is_purchasable: false,
    is_stripe_linked: false,
  },
  {
    id: "static_agency",
    plan_code: "agency",
    name: "Agency",
    description: "For agencies collaborating across proposals and analytics.",
    stripe_price_id: null,
    stripe_product_id: null,
    billing_cycle: "monthly",
    price_cents: 4900,
    currency: "usd",
    features: [
      "Everything in Pro",
      "Up to 10 team members",
      "Team analytics",
      "Custom branding",
    ],
    limits: {
      proposals_per_month: null,
      job_analyses_per_month: null,
      knowledge_base_files: 50,
      team_members: 10,
      workspaces: 3,
    },
    is_active: true,
    is_public: true,
    sort_order: 3,
    created_at: NOW,
    updated_at: NOW,
    price_display: "$49/mo",
    is_purchasable: false,
    is_stripe_linked: false,
  },
  {
    id: "static_enterprise",
    plan_code: "enterprise",
    name: "Enterprise",
    description: "Custom limits, security, and onboarding for larger teams.",
    stripe_price_id: null,
    stripe_product_id: null,
    billing_cycle: "custom",
    price_cents: null,
    currency: "usd",
    features: [
      "Custom usage limits",
      "Dedicated onboarding",
      "SSO and advanced security",
      "Priority SLA support",
    ],
    limits: {
      proposals_per_month: null,
      job_analyses_per_month: null,
      knowledge_base_files: null,
      team_members: null,
      workspaces: null,
    },
    is_active: true,
    is_public: true,
    sort_order: 4,
    created_at: NOW,
    updated_at: NOW,
    price_display: "Contact us",
    is_purchasable: false,
    is_stripe_linked: false,
  },
];
